### ISSUE TITLE
Problem linking python311.lib

### ISSUE THREAD

**Issue by NairoDorian** [IntentDev/PluginBuilder#6]
When trying to create Plugin based on the CHOPWithPythonClass I get this error

...\PluginBuilder\TestChop\PluginProjects\Zop>ninja -C build
ninja: Entering directory `build'
[1/2] Building CXX object CMakeFiles\Zop.dir\source\Zop.cpp.obj
[2/2] Linking CXX shared library bin\Release\Zop.dll
FAILED: bin/Release/Zop.dll lib/Release/Zop.lib 
C:\WINDOWS\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\Zop.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\link.exe /nologo CMakeFiles\Zop.dir\source\Zop.cpp.obj  /out:bin\Release\Zop.dll /implib:lib\Release\Zop.lib /pdb:bin\Release\Zop.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO -LIBPATH:...\PluginBuilder\3rdParty\Python\lib\x64 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\link.exe /nologo CMakeFiles\Zop.dir\source\Zop.cpp.obj /out:bin\Release\Zop.dll /implib:lib\Release\Zop.lib /pdb:bin\Release\Zop.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO -LIBPATH:...\PluginBuilder\3rdParty\Python\lib\x64 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST:EMBED,ID=2" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'python311.lib'

Any ideas on how to fix that ?

**Comment by keithlostracco** [comment]
I pushed an update that should resolve your issue. The .gitignore was ignoring all .lib files so the 3rd party libs were never committed to the repository. They are now included. If you fetch and pull the updates the project should compile without issue...

**Comment by NairoDorian** [comment]
Thank you works as intended now !

**Comment by NairoDorian** [comment]
Thank you works as intended now !

**Comment by keithlostracco** [comment]
Perfect!
